### ISSUE TITLE
Failed to communicate with "/interface-data/init?1650471343718", with status: [500 (error)] Internal Server Error

### ISSUE THREAD

**Issue by JoBilert** [lucapisciotta/calibre#9]
Hi, I tried a new install of your container cause it really sounded like what I needed. 

But whenever I call up the  webinterface, I see the following Errormessage:

*Failed to communicate with "/interface-data/init?1650471343718", with status: [500 (error)] Internal Server Error*

Do you have any idea what I could do to make it work?

**Comment by lucapisciotta** [comment]
Mmm it's a little bit strange, i'm using it daily without any problems. Unfortunately i'm not the developers of that package but try some steps:

- The folder `/books` has the right permissions to be used from the container?
- Do you use a proxy? seems on the official forum that in the past there was some problems related to that.
- Have you enabled some security rules on the firewall or in the machine? [[link](https://www.mobileread.com/forums/showthread.php?t=294382)]

**Comment by JoBilert** [comment]
> Mmm it's a little bit strange, i'm using it daily without any problems. Unfortunately i'm not the developers of that package but try some steps:
> 
> * The folder `/books` has the right permissions to be used from the container?

To be honest, I am not entirely sure about the  folder-rights. I assumed they should be ok since I used the same setup with COPS and Calibre-Web before.

> * Do you use a proxy? seems on the official forum that in the past there was some problems related to that.
> * Have you enabled some security rules on the firewall or in the machine? [[link]
(https://www.mobileread.com/forums/showthread.php?t=294382)]

I have no special proxy or firewall in the setup yet, but was using it purely via local IP and port.

**Comment by JoBilert** [comment]
Hey sure, no hurry. This isn't a live-or-death thing. Send a message and I will gladly test a new version, whenever it is available.

**Comment by lucapisciotta** [comment]
@JoBilert i've pushed a new release on docker hub with the latest version of calibre and (I hope 😄 ) the fix you needed.
I've added the possibility to change the userid and groupid directly with the environment variables (similar to what did by linuxserver), can you try if it works?

**Comment by JoBilert** [comment]
Still getting *Failed to communicate with "/interface-data/init?1652554872912", with status: [500 (error)] Internal Server Error* And the Log says :
*apsw.BusyError: BusyError: database is locked*

```version: '3.8'
services:
    calibre:
        image: lucapisciotta/calibre:latest
        container_name: calibre
        environment:
            #- ENABLE_AUTH=true
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin    
        volumes:
            - /home/pi/books:/books
            - /home/pi/calibreserv/users.sqlite:/srv/calibre/users.sqlite
        ports:
            - 8131:8085
        restart: unless-stopped
       

Is there maybe something wrong with my compose?

**Comment by lucapisciotta** [comment]
Which are the uid and gid of the owner of your library?
________________________________

**Comment by lucapisciotta** [comment]
@JoBilert wait seems a problem related to the database, are you running your container with also your client already started?

**Comment by JoBilert** [comment]
I mounted the library from a separate NAS. I remounted it using UID and GID 1000 same as in the container, but it didn't help.

About the other message, I am not sure what you mean by "running the container with my client already started". What client are you referring to?

I start up the container and then point my browser to the address and port of the container.

**Comment by JoBilert** [comment]
With `ENABLE_AUTH= true` and the volume for sqlite commented out I get 
``` 
Failed to communicate with "/interface-data/init?1652900475954", with status: [400 (error)] Bad Request

Digest algorithm required fields missing

**Comment by lucapisciotta** [comment]
Why commented out? to use the authentication you need to enable auth and pass to the container your sqlite database, if you look into the entrypoint you can see that if the db exists (the one you passed on it) it tries to use it.
Another test should be, copy the database and set 777 as permission on it (i know isn't so good 😞 ) but only to understand if it's a permission problem

**Comment by JoBilert** [comment]
If I turn on the authentification, I get asked for login and I only know the Password but no login name.
BTW: the Container never even created a sqlite-file in the folder and I don't know how to create one.

**Comment by lucapisciotta** [comment]
Ok, i've released a new version and i've added fixuid to manage differently the ID, can you try now? Instead of using PUID and PGID you need to use the user functionality

**Comment by JoBilert** [comment]
Sooo, I hope I understood you right. I commented the PUID and PGID out; have Authentification enabled and an Admin-Password set.

I have a very rudimentary users.sqlite (seems to be just a header and no user entry).
I call up the website get asked for authentification and enter the password (no username) and still get the 
```
Failed to communicate with "/interface-data/init?1654273492507", with status: [400 (error)] Bad Request

Digest algorithm required fields missing
```
Sorry, maybe I am just too stupid, but it still doesn't work.

**Comment by lucapisciotta** [comment]
Ahahahah don't worry, you're not stupid. In any case correct the comment on PUID and PGID but you need to add the option `user: 1000:1000` if you're using docker compose or `-u 1000:1000` if you're using docker directly.
`1000` it's only an example, you need to use the right user id that is the owner of the files in your share.

**Comment by JoBilert** [comment]
Ok, I did what you said. Redid the whole docker-compose and it seems to get me a bit further... except for the fact, that docker-compose keeps creating a directory called users.sqlite instead of a file.

**Comment by lucapisciotta** [comment]
Ok, maybe we're near to the resolution, can you try with the latest release?

**Comment by JoBilert** [comment]
In the Portainer console I get no more errors, but in the browser the problem consists,
Do i need to enter a Username or do i leave that field empty?

The Console shows this after trying to log on:
```
192.168.2.xxx port-55959 - 08/Jun/2022:23:10:17 +0200 "GET / HTTP/1.1" 304 135
192.168.2.xxx port-55959 - 08/Jun/2022:23:10:18 +0200 "GET /ajax-setup?1654722605512 HTTP/1.1" 200 369
192.168.2.xxx port-55959 - 08/Jun/2022:23:10:18 +0200 "GET /favicon.png HTTP/1.1" 200 17743
192.168.2.xxx port-55961 - 08/Jun/2022:23:10:18 +0200 "GET /interface-data/init?1654722605571 HTTP/1.1" 401 292
192.168.2.xxx port-55961 - 08/Jun/2022:23:10:23 +0200 "GET /interface-data/init?1654722605571 HTTP/1.1" 400 166
```

**Comment by lucapisciotta** [comment]
You need to put "admin" for the default user

**Comment by JoBilert** [comment]
Hey, I have seen you did another Update and I tried it right away but getting the same error as in the last post.
I checked the */srv/calibre* directory in the container and can confirm that there is a *user.sqlite* file with a user *admin and my password* in it.

**Comment by lucapisciotta** [comment]
Sorry @JoBilert, i've tried a lot but I can't duplicate your error

**Comment by JoBilert** [comment]
Hey, no problem, it means a lot to me that you even tried. I will follow your project nevertheless...

Maybe I can find out, what I have been doing wrong all the time and then feed back to you.

**Comment by lucapisciotta** [comment]
Hi @JoBilert, i've found that, using a shared folder, there are some known problems directly from the calibre forum.
In these weeks i've moved my library to a shared folder and I've encountered some similar problems that you had and I've solved them using these options in the volume definition:
```yaml
volumes:
  books:
    driver_opts:
      type: cifs
      o: "user=guest,guest,rw,soft,nobrl,noserverino,noperm"
      device: "//MY_SHARED_FOLDER_IP/Books"`
```
Try to see if it works for you :)

**Comment by JoBilert** [comment]
> ```yaml
> books:
>     driver_opts:
>       type: cifs
>       o: "user=guest,guest,rw,soft,nobrl,noserverino,noperm"
>       device: "//MY_SHARED_FOLDER_IP/Books
> ```

Hey thanks for getting back at me with this solution. I will try it and let you know if I make any progress.
